/* Import des Types */
import type { CardsTrottinetteBrand_data_Type } from "../../../../../types/produits/cardsTrottinetteBrand.data.type";

/* Import des composants Router */
import router from "../../../../../router/router";

function dualtron_Data() {
    const tab: CardsTrottinetteBrand_data_Type = [
        {
            reactKey: 1,
            image: "/images/produits/trottinette/dualtron/dualtron-x-ltd/dualtron-x-ltd-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![1].path + "#top",
            model: "Dualtron X LTD",
            price: "5949 €",
            battery: "84V 60Ah", 
            power: "13300W",
            range: "170 km",
        },
        {
            reactKey: 2,
            image: "/images/produits/trottinette/dualtron/dualtron-storm-ltd/dualtron-storm-ltd-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![2].path + "#top",
            model: "Dualtron Storm LTD",
            price: "4249 €",
            battery: "84V 45Ah", 
            power: "11500W",
            range: "180 km",
        },
        {
            reactKey: 3,
            image: "/images/produits/trottinette/dualtron/dualtron-alien/dualtron-alien-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![3].path + "#top",
            model: "Dualtron Alien",
            price: "3949 €",
            battery: "72V 40Ah", 
            power: "11200W",
            range: "125 km",
        },
        {
            reactKey: 4,
            image: "/images/produits/trottinette/dualtron/dualtron-thunder-3/dualtron-thunder-3-n01-powerwatt34.webp",
            path: router[4]!.children![1]!.children![7].path + "#top",
            model: "Dualtron Thunder 3",
            price: "3049 €",
            battery: "72V 40Ah", 
            power: "10800W",
            range: "150 km",
        },
        {
            reactKey: 5,
            image: "/images/produits/trottinette/dualtron/dualtron-thunder-2/dualtron-thunder-2-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![6].path + "#top",
            model: "Dualtron Thunder 2",
            price: "2749 €",
            battery: "72V 40Ah", 
            power: "10080W",
            range: "120 km",
        },
        {
            reactKey: 6,
            image: "/images/produits/trottinette/dualtron/dualtron-achilleus-rouge/dualtron-achilleus-rouge-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![5].path + "#top",
            model: "Dualtron Achilleus Rouge",
            price: "2449 €",
            battery: "60V 35Ah", 
            power: "4648W",
            range: "120 km",
        },
        {
            reactKey: 7,
            image: "/images/produits/trottinette/dualtron/dualtron-achilleus/dualtron-achilleus-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![4].path + "#top",
            model: "Dualtron Achilleus",
            price: "2449 €",
            battery: "60V 35Ah", 
            power: "4648W",
            range: "120 km",
        },
        {
            reactKey: 8,
            image: "/images/produits/trottinette/dualtron/dualtron-victor-ltd/dualtron-victor-ltd-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![8].path + "#top",
            model: "Dualtron Victor LTD",
            price: "2649 €",
            battery: "60V 35Ah Samsung", 
            power: "4000W",
            range: "120 km",
        },
        {
            reactKey: 9,
            image: "/images/produits/trottinette/dualtron/dualtron-victor-ltd/dualtron-victor-ltd-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![9].path + "#top",
            model: "Dualtron Victor LTD",
            price: "2449 €",
            battery: "60V 35Ah", 
            power: "4000W",
            range: "110 km",
        },
        {
            reactKey: 10,
            image: "/images/produits/trottinette/dualtron/dualtron-victor-ltd/dualtron-victor-ltd-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![11].path + "#top",
            model: "Dualtron Victor LTD",
            price: "2349 €",
            battery: "60V 31Ah", 
            power: "4000W",
            range: "100 km",
        },
        {
            reactKey: 11,
            image: "/images/produits/trottinette/dualtron/dualtron-victor-ltd/dualtron-victor-ltd-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![12].path + "#top",  
            model: "Dualtron Victor LTD",
            price: "2249 €",
            battery: "60V 28Ah", 
            power: "4000W",
            range: "90 km",
        },
        {
            reactKey: 12,
            image: "/images/produits/trottinette/dualtron/dualtron-victor-luxury-plus/dualtron-victor-luxury-plus-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![10].path + "#top",
            model: "Dualtron Victor Luxury Plus",
            price: "2449 €",
            battery: "60V 35Ah Samsung", 
            power: "4400W",
            range: "120 km",
        },
        {
            reactKey: 13,
            image: "/images/produits/trottinette/dualtron/dualtron-victor-luxury-plus/dualtron-victor-luxury-plus-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![15].path + "#top",
            model: "Dualtron Victor Luxury Plus",
            price: "2249 €",
            battery: "60V 35Ah", 
            power: "4000W",
            range: "110 km",
        },
        {
            reactKey: 14,
            image: "/images/produits/trottinette/dualtron/dualtron-victor-luxury-plus/dualtron-victor-luxury-plus-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![14].path + "#top",
            model: "Dualtron Victor Luxury Plus",
            price: "2149 €",
            battery: "60V 31Ah", 
            power: "4000W",
            range: "100 km",
        },
        {
            reactKey: 15,
            image: "/images/produits/trottinette/dualtron/dualtron-victor-luxury-plus/dualtron-victor-luxury-plus-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![13].path + "#top",
            model: "Dualtron Victor Luxury Plus",
            price: "1949 €",
            battery: "60V 28Ah", 
            power: "4000W",
            range: "90 km",
        },
        {
            reactKey: 16,
            image: "/images/produits/trottinette/dualtron/dualtron-city/dualtron-city-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![16].path + "#top",
            model: "Dualtron City",
            price: "1649 €",
            battery: "60V 20Ah", 
            power: "4000W",
            range: "70 km",
        },
        {
            reactKey: 17,
            image: "/images/produits/trottinette/dualtron/dualtron-new-city/dualtron-new-city-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![17].path + "#top",
            model: "Dualtron New City",
            price: "1849 €",
            battery: "60V 20Ah", 
            power: "4000W",
            range: "70 km",
        },
        {
            reactKey: 18,
            image: "/images/produits/trottinette/dualtron/dualtron-new-city/dualtron-new-city-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![18].path + "#top",
            model: "Dualtron New City",
            price: "1949 €",
            battery: "60V 22,5Ah", 
            power: "4000W",
            range: "80 km",
        },
        {
            reactKey: 19,
            image: "/images/produits/trottinette/dualtron/dualtron-new-city/dualtron-new-city-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![19].path + "#top",
            model: "Dualtron New City",
            price: "2049 €",
            battery: "60V 25Ah",
            power: "4000W",
            range: "90 km",
        },
        {
            reactKey: 20,
            image: "/images/produits/trottinette/dualtron/dualtron-spider-max/dualtron-spider-max-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![20].path + "#top",
            model: "Dualtron Spider Max",
            price: "1449 €",
            battery: "60V 27Ah",
            power: "4000W",
            range: "85 km",
        },
        {
            reactKey: 21,
            image: "/images/produits/trottinette/dualtron/dualtron-spider-max/dualtron-spider-max-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![21].path + "#top",
            model: "Dualtron Spider Max",
            price: "1549 €",
            battery: "60V 30Ah",
            power: "4000W",
            range: "100 km",
        },
        {
            reactKey: 22,
            image: "/images/produits/trottinette/dualtron/dualtron-victor/dualtron-victor-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![24].path + "#top",
            model: "Dualtron Victor",
            price: "1649 €",
            battery: "60V 30Ah",
            power: "4000W",
            range: "95 km",
        },
        {
            reactKey: 23,
            image: "/images/produits/trottinette/dualtron/dualtron-victor/dualtron-victor-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![23].path + "#top",
            model: "Dualtron Victor",
            price: "1599 €",
            battery: "60V 27Ah",
            power: "4000W",
            range: "85 km",
        },
        {
            reactKey: 24,
            image: "/images/produits/trottinette/dualtron/dualtron-victor/dualtron-victor-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![22].path + "#top",
            model: "Dualtron Victor",
            price: "1549 €",
            battery: "60V 24Ah", 
            power: "4000W",
            range: "75 km",
        },
        {
            reactKey: 25,
            image: "/images/produits/trottinette/dualtron/dualtron-aminia-double-moteur/dualtron-aminia-double-moteur-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![28].path + "#top",
            model: "Dualtron Aminia Double Moteur",
            price: "1349 €",
            battery: "52V 21Ah", 
            power: "2900W",
            range: "65 km",
        },
        {
            reactKey: 26,
            image: "/images/produits/trottinette/dualtron/dualtron-aminia-double-moteur/dualtron-aminia-double-moteur-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![26].path + "#top",
            model: "Dualtron Aminia Double Moteur",
            price: "849 €",
            battery: "52V 15,6Ah", 
            power: "2900W",
            range: "50 km",
        },
        {
            reactKey: 27,
            image: "/images/produits/trottinette/dualtron/dualtron-aminia/dualtron-aminia-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![27].path + "#top",
            model: "Dualtron Aminia",
            price: "979 €",
            battery: "52V 17,5Ah", 
            power: "1450W",
            range: "60 km",
        },
        {
            reactKey: 28,
            image: "/images/produits/trottinette/dualtron/dualtron-aminia/dualtron-aminia-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![25].path + "#top",
            model: "Dualtron Aminia",
            price: "749 €",
            battery: "52V 13Ah", 
            power: "1450W",
            range: "45 km",
        },
        {
            reactKey: 29,
            image: "/images/produits/trottinette/dualtron/dualtron-forever-limited/dualtron-forever-limited-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![32].path + "#top",
            model: "Dualtron Forever Limited",
            price: "1449 €",
            battery: "60V 30Ah", 
            power: "2900W",
            range: "80 km",
        },
        {
            reactKey: 30,
            image: "/images/produits/trottinette/dualtron/dualtron-forever-limited/dualtron-forever-limited-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![31].path + "#top",
            model: "Dualtron Forever Limited",
            price: "1399 €",
            battery: "60V 27Ah", 
            power: "2900W",
            range: "70 km",
        },
        {
            reactKey: 31,
            image: "/images/produits/trottinette/dualtron/dualtron-forever-limited/dualtron-forever-limited-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![30].path + "#top",
            model: "Dualtron Forever Limited",
            price: "1349 €",
            battery: "60V 24Ah", 
            power: "2900W",
            range: "60 km",
        },
        {
            reactKey: 32,
            image: "/images/produits/trottinette/dualtron/dualtron-forever-limited/dualtron-forever-limited-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![29].path + "#top",
            model: "Dualtron Forever Limited",
            price: "1249 €",
            battery: "60V 18,2Ah", 
            power: "2900W",
            range: "50 km",
        },
        {
            reactKey: 33,
            image: "/images/produits/trottinette/dualtron/dualtron-forever/dualtron-forever-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![33].path + "#top",
            model: "Dualtron Forever",
            price: "1179 €",
            battery: "60V 27Ah", 
            power: "2900W",
            range: "70 km",
        },
        {
            reactKey: 34,
            image: "/images/produits/trottinette/dualtron/dualtron-forever/dualtron-forever-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![34].path + "#top",
            model: "Dualtron Forever",
            price: "1099 €",
            battery: "60V 18Ah", 
            power: "2900W",
            range: "50 km",
        },
        {
            reactKey: 35,
            image: "/images/produits/trottinette/dualtron/dualtron-pop/dualtron-pop-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![35].path + "#top",
            model: "Dualtron Pop",
            price: "1049 €",
            battery: "52V 25Ah", 
            power: "1450W",
            range: "50 km",
        },
        {
            reactKey: 36,
            image: "/images/produits/trottinette/dualtron/dualtron-pop-double-moteur/dualtron-pop-double-moteur-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![36].path + "#top",
            model: "Dualtron Pop Double Moteur",
            price: "1249 €",
            battery: "52V 20Ah", 
            power: "2900W",
            range: "40 km",
        },
        {
            reactKey: 37,
            image: "/images/produits/trottinette/dualtron/dualtron-togo-max/dualtron-togo-max-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![40].path + "#top",
            model: "Dualtron Togo Max",
            price: "949 €",
            battery: "60V 15,9Ah", 
            power: "1200W",
            range: "50 km",
        },
        {
            reactKey: 38,
            image: "/images/produits/trottinette/dualtron/dualtron-togo-ltd/dualtron-togo-ltd-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![39].path + "#top",
            model: "Dualtron Togo LTD",
            price: "879 €",
            battery: "60V 15Ah Samsung", 
            power: "1200W",
            range: "50 km",
        },
        {
            reactKey: 39,
            image: "/images/produits/trottinette/dualtron/dualtron-togo-ltd/dualtron-togo-ltd-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![38].path + "#top",
            model: "Dualtron Togo LTD",
            price: "849 €",
            battery: "60V 15Ah", 
            power: "1200W",
            range: "50 km",
        },
        {
            reactKey: 40,
            image: "/images/produits/trottinette/dualtron/dualtron-togo-ltd/dualtron-togo-ltd-n01-powerwatt34.jpg",
            path: router[4]!.children![1]!.children![37].path + "#top",
            model: "Dualtron Togo LTD",
            price: "779 €",
            battery: "60V 12Ah", 
            power: "1200W",
            range: "40 km",
        },
        {
            reactKey: 41,
            image: "/images/produits/trottinette/dualtron/dualtron-togo-pro/dualtron-togo-pro-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Togo Pro",
            price: "679 €",
            battery: "48V 13,5Ah", 
            power: "920W",
            range: "35 km",
        },
        {
            reactKey: 42,
            image: "/images/produits/trottinette/dualtron/dualtron-togo-plus/dualtron-togo-plus-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Togo Plus",
            price: "579 €",
            battery: "36V 12Ah", 
            power: "800W",
            range: "35 km",
        },
        {
            reactKey: 43,
            image: "/images/produits/trottinette/dualtron/dualtron-togo-plus/dualtron-togo-plus-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Togo Plus",
            price: "615 €",
            battery: "48V 12Ah", 
            power: "800W",
            range: "50 km",
        },
        {
            reactKey: 44,
            image: "/images/produits/trottinette/dualtron/dualtron-sonic-pro/dualtron-sonic-pro-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Sonic Pro",
            price: "649 €",
            battery: "36V 10Ah", 
            power: "700W",
            range: "30 km",
        },
    ]

    return (tab);
}

export { dualtron_Data };
