/* Import des Types */
import type { CardsTrottinetteBrand_data_Type } from "../../../../../types/produits/cardsTrottinetteBrand.data.type";

function dualtron_Data() {
    const tab: CardsTrottinetteBrand_data_Type = [
        {
            reactKey: 1,
            image: "/images/produits/trottinette/dualtron/dualtron-x-ltd/dualtron-x-ltd-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron X LTD",
            price: "5949 €",
            battery: "84V 60Ah", 
            power: "13300W",
            range: "170 km",
        },
        {
            reactKey: 2,
            image: "/images/produits/trottinette/dualtron/dualtron-storm-ltd/dualtron-storm-ltd-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Storm LTD",
            price: "4249 €",
            battery: "84V 45Ah", 
            power: "11500W",
            range: "180 km",
        },
        {
            reactKey: 3,
            image: "/images/produits/trottinette/dualtron/dualtron-alien/dualtron-alien-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Alien",
            price: "3949 €",
            battery: "72V 40Ah", 
            power: "11200W",
            range: "125 km",
        },
        {
            reactKey: 4,
            image: "/images/produits/trottinette/dualtron/dualtron-thunder-3/dualtron-thunder-3-n01-powerwatt34.webp",
            path: "#",
            model: "Dualtron Thunder 3",
            price: "3449 €",
            battery: "72V 40Ah", 
            power: "10800W",
            range: "150 km",
        },
        {
            reactKey: 5,
            image: "/images/produits/trottinette/dualtron/dualtron-thunder-2/dualtron-thunder-2-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Thunder 2",
            price: "2949 €",
            battery: "72V 40Ah", 
            power: "10080W",
            range: "120 km",
        },
        {
            reactKey: 6,
            image: "/images/produits/trottinette/dualtron/dualtron-achilleus-rouge/dualtron-achilleus-rouge-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Achilleus Rouge",
            price: "2449 €",
            battery: "60V 35Ah", 
            power: "4648W",
            range: "120 km",
        },
        {
            reactKey: 7,
            image: "/images/produits/trottinette/dualtron/dualtron-achilleus/dualtron-achilleus-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Achilleus",
            price: "2449 €",
            battery: "60V 35Ah", 
            power: "4648W",
            range: "120 km",
        },
        {
            reactKey: 8,
            image: "/images/produits/trottinette/dualtron/dualtron-victor-ltd/dualtron-victor-ltd-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Victor LTD",
            price: "2649 €",
            battery: "60V 35Ah Samsung", 
            power: "4000W",
            range: "120 km",
        },
        {
            reactKey: 9,
            image: "/images/produits/trottinette/dualtron/dualtron-victor-ltd/dualtron-victor-ltd-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Victor LTD",
            price: "2449 €",
            battery: "60V 35Ah", 
            power: "4000W",
            range: "110 km",
        },
        {
            reactKey: 10,
            image: "/images/produits/trottinette/dualtron/dualtron-victor-ltd/dualtron-victor-ltd-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Victor LTD",
            price: "2349 €",
            battery: "60V 31Ah", 
            power: "4000W",
            range: "100 km",
        },
        {
            reactKey: 11,
            image: "/images/produits/trottinette/dualtron/dualtron-victor-ltd/dualtron-victor-ltd-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Victor LTD",
            price: "2249 €",
            battery: "60V 28Ah", 
            power: "4000W",
            range: "90 km",
        },
        {
            reactKey: 12,
            image: "/images/produits/trottinette/dualtron/dualtron-victor-luxury-plus/dualtron-victor-luxury-plus-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Victor Luxury Plus",
            price: "2449 €",
            battery: "60V 35Ah Samsung", 
            power: "4000W",
            range: "120 km",
        },
        {
            reactKey: 13,
            image: "/images/produits/trottinette/dualtron/dualtron-victor-luxury-plus/dualtron-victor-luxury-plus-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Victor Luxury Plus",
            price: "2249 €",
            battery: "60V 35Ah", 
            power: "4000W",
            range: "110 km",
        },
        {
            reactKey: 14,
            image: "/images/produits/trottinette/dualtron/dualtron-victor-luxury-plus/dualtron-victor-luxury-plus-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Victor Luxury Plus",
            price: "2149 €",
            battery: "60V 31Ah", 
            power: "4000W",
            range: "100 km",
        },
        {
            reactKey: 15,
            image: "/images/produits/trottinette/dualtron/dualtron-victor-luxury-plus/dualtron-victor-luxury-plus-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Victor Luxury Plus",
            price: "1949 €",
            battery: "60V 28Ah", 
            power: "4000W",
            range: "90 km",
        },
        {
            reactKey: 16,
            image: "/images/produits/trottinette/dualtron/dualtron-city/dualtron-city-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron City",
            price: "2249 €",
            battery: "60V 25Ah", 
            power: "4000W",
            range: "80 km",
        },
        {
            reactKey: 17,
            image: "/images/produits/trottinette/dualtron/dualtron-city/dualtron-city-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron City",
            price: "2149 €",
            battery: "60V 25Ah", 
            power: "4000W",
            range: "65 km",
        },
        {
            reactKey: 18,
            image: "/images/produits/trottinette/dualtron/dualtron-city/dualtron-city-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron City",
            price: "1949 €",
            battery: "60V 25Ah", 
            power: "4000W",
            range: "50 km",
        },
        {
            reactKey: 19,
            image: "/images/produits/trottinette/dualtron/dualtron-spider-max/dualtron-spider-max-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Spider Max",
            price: "1949 €",
            battery: "60V 30Ah", 
            power: "4000W",
            range: "100 km",
        },
        {
            reactKey: 20,
            image: "/images/produits/trottinette/dualtron/dualtron-victor/dualtron-victor-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Victor",
            price: "1649 €",
            battery: "60V 30Ah", 
            power: "4000W",
            range: "95 km",
        },
        {
            reactKey: 21,
            image: "/images/produits/trottinette/dualtron/dualtron-victor/dualtron-victor-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Victor",
            price: "1599 €",
            battery: "60V 27Ah", 
            power: "4000W",
            range: "85 km",
        },
        {
            reactKey: 22,
            image: "/images/produits/trottinette/dualtron/dualtron-victor/dualtron-victor-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Victor",
            price: "1549 €",
            battery: "60V 24Ah", 
            power: "4000W",
            range: "75 km",
        },
        {
            reactKey: 23,
            image: "/images/produits/trottinette/dualtron/dualtron-aminia-double-moteur/dualtron-aminia-double-moteur-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Aminia Double Moteur",
            price: "1349 €",
            battery: "52V 21Ah", 
            power: "2900W",
            range: "50 km",
        },
        {
            reactKey: 24,
            image: "/images/produits/trottinette/dualtron/dualtron-aminia-double-moteur/dualtron-aminia-double-moteur-n01-powerwatt34.jpg",
            path: "#",
            model: "Dualtron Aminia Double Moteur",
            price: "979 €",
            battery: "52V 15,6Ah", 
            power: "2900W",
            range: "40 km",
        },
    ]

    return (tab);
}

export { dualtron_Data };
