name: Déploiement en Production

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    name: Déploiement VPS
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v3

      - name: 🔐 Connexion SSH via clé privée
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 🚀 Déployer sur le VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e  # Stoppe à la moindre erreur

            echo "📁 Accès au dossier du projet"
            cd ${{ secrets.PROJECT_PATH }}

            echo "✅ Etape 1/8 : PRUNE AVANT L'ARRÊT — conditionnel pour protéger la DB si tout est déjà down"

            # Nettoie uniquement les caches BuildKit
            sudo docker builder prune -af || true

            echo "Etape 1.1 - Listage des conteneurs actifs"
            ACTIVE_CONTAINERS="$(sudo docker ps -q)"

            if [ -z "$ACTIVE_CONTAINERS" ]; then
              echo "ℹ️ Aucun conteneur actif -> prune SANS --volumes (protection DB)"
              sudo docker system prune -af || true

            else
              echo "ℹ️ Conteneurs actifs détectés"

              # Création d'une variable = au nom du conteneur DB (nom réel récupérable via 'docker ps')
              DB_CONTAINER="db"

              echo "ℹ️ Vérification si le conteneur DB est actif"
              if sudo docker ps --format '{{.Names}}' | grep -qx "$DB_CONTAINER"; then



















            if [ -z "$(sudo docker ps -q)" ]; then
              echo "ℹ️ Aucun conteneur actif -> prune SANS --volumes (protection DB)"
              sudo docker system prune -af || true
            else
              echo "ℹ️ Conteneurs actifs -> prune AVEC --volumes (les volumes utilisés sont protégés)"
              sudo docker system prune -af --volumes || true
            fi

            echo "🛑 Etape 2/8 : Stop + remove containers : Phase 1/2"
            sudo docker stop $(sudo docker ps -q) || true
            sudo docker rm $(sudo docker ps -aq) || true

            echo "🧹 Etape 3/8 : Suppression du volume client-dist"
            sudo docker volume rm l-atelier_photo_montpellier_client-dist || true

            echo "🧹 Etape 4/8 : Suppression du volume client-kaleidopix-dist"
            sudo docker volume rm l-atelier_photo_montpellier_client-kaleidopix-dist || true

            echo "🔀 Etape 5/8 : Checkout de la bonne branche"
            git checkout Deploy

            echo "🚀 Etape 6/8 : Build + redémarrage : Phase 1/2"
            git pull origin Deploy
            sudo docker compose up -d --build

            echo "🛑 Etape 7/8 : Arrêt des containers : Phase 2/2"
            sudo docker compose down || true

            echo "🚢 Etape 8/8 : Redémarrage des containers : Phase 2/2"
            sudo docker compose up -d

            echo "✅ Déploiement terminé"
          EOF
